name: twogether

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: twogether
      POSTGRES_PASSWORD: twogether
      POSTGRES_USER: twogether
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data

volumes:
  database:
  rabbitmq:
  # redis:
